### ISSUE TITLE
Exercise downloader should use tmc-langs unzipper.

### ISSUE THREAD

**Issue by samutamm** [testmycode/tmc-core#14] opened 2015-07-24 11:39 UTC

**Comment by samutamm** [comment] 2015-07-27 07:21
Tmc-langs unzipping (and zipping) uses StudentFilePolicy-object to decide, which files should be zipped and unzipped. The logic for choosing correct StudentFilePolicy can be implemented to eiher tmc-core or tmc-langs. This decision should be made when tmc-langs-experts (Loezi/Jamo) come to work.

**Comment by zinkko** [comment] 2015-08-04 11:50
a duplicate of this has been merged

**Closed as completed by zinkko** 2015-08-04 11:50 UTC
